{{- if not .Values.existingConfigSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hoocloak.configSecretName" . }}
  labels:
    {{- include "hoocloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
    {{- toYaml .Values.hoocloakConfig | nindent 4 }}
{{- end }}
